### ISSUE TITLE
Using both SecuredText and TextSecure

### ISSUE THREAD

**Issue by johanw666** [SecuredText/SecuredText#1]
In the migrating section is written to remove TextSecure. However, when I want to use SecuredText as a secure sms replacement and keep TextSecure as a dedicated messenger to communicate with people using an iPhone, is this possible? I would assume it is if both projects have a different package name.

**Comment by BastienLQ** [comment]
Yes, this is currently not possible to have TextSecure and SecuredText at the same time. Package names are different (`org.SecuredText.SecuredText` vs. `org.thoughtcrime.securesms`).

**Comment by landry314** [comment]
This is likely because the background processes which grab incoming messages will fight with each other because the format of encrypted messages are identical.

ultimately it would be a great to find a way to allow them both to run.
