### ISSUE TITLE
Remove Floating Blue Circle, Put it Back in the Title Bar

### ISSUE THREAD

**Issue by landry314** [SecuredText/SecuredText#2]
In version 2.5 I believe, TextSecure decided to move the + sign to create a new message from its neat home in the title bar to a floating blue circle which covers part of the lowest conversation. I believe this was done to make it look more like WhatsApp...

It is annoying, ugly, and should be reversed in my opinion. Anyone agree?

**Comment by BastienLQ** [comment]
Can you find the commit in TextSecure? I think this change was made to have the new Google Material UI.

I would prefer to maintain SecuredText similar to TextSecure for other functionalities than SMS encryption and Push messages related questions. But if it is technically possible, we could maintain a separated theme with the legacy UI.

**Comment by landry314** [comment]
i guess you are right. if you will be incorporating updates of textsecure into securedtext then keeping it as similar as possible except for push and sms features would be the easiest and cleanest.

But, textsecure will not be updating any sms features so... what are your plans for securedtext?

**Comment by BastienLQ** [comment]
My plans are to keep SMS encryption and add SecuredText in F-Droid (MR pending here: https://gitlab.com/fdroid/fdroiddata/merge_requests/646).

I think TextSecure's devs made a huge mistake when then decided to add push messages in a SMS app; I hope one day they will put push messages in another app than TextSecure, keeping only SMS functionalities (and encryption) in TextSecure.

So plans are to be what TextSecure should be: an SMS app, and only that. For now, I don't have time to add functionalities other than those in TextSecure. But any help will be appreciated and discussion is opened.

**Comment by landry314** [comment]
I totally agree that it was a huge mistake to add push messaging. They should really combine Red Phone and TextSecure into "Signal for Android" and keep TextSecure as a simple SMS Encryption app, but they won't and they never will, hope is lost. Moxie is completely committed to destroying the original point of TextSecure and making it into an IM client which I am vehemently opposed to.

So, SecuredText will follow TextSecure's updates but just include SMS and exclude push, am I right? This is a good idea.

I am 100% behind SecuredText and I will promote it the best I can. Any help with promotions, just ask.

**Comment by BastienLQ** [comment]
You're right. Adding other functionalities is not excluded, but I do not have time for.
